name: Scrape latest location XML

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '27,57 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://www.givefood.org.uk/api/2/locations/?format=xml > locations.xml
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest location XML data: ${timestamp}" || exit 0
        git push
