name: Scrape latest IFAN food banks

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '45 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest IFAN KML data
      run: |-
        curl https://www.google.com/maps/d/u/0/kml?mid=1r8XyrXu-aFXnVaEVgegVquyIt94quP0q&forcekml=1 > ifan.kml
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest IFAN food banks data: ${timestamp}" || exit 0
        git push
