name: Scrape latest IFAN foodbanks

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '10,40 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest IFAN JSON
      run: |-
        curl https://www.givefood.org.uk/proxy/ifan/ > ifan.xml
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest IFAN food bank data: ${timestamp}" || exit 0
        git push
