name: Scrape latest location YAML

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '25,55 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://www.givefood.org.uk/api/2/locations/?format=yaml > locations.yaml
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest location YAML data: ${timestamp}" || exit 0
        git push
